In [1]:
import numpy as np

In [2]:
array1 = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

In [3]:
array1

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31])

In [4]:
type(array1)

numpy.ndarray

In [5]:
array1.shape

(11,)

In [6]:
array2 = np.array([[1, 2, 3, 4 ],[5, 6, 7, 8], [9, 10, 11, 12]])

In [7]:
type(array2)

numpy.ndarray

In [8]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
# 2차원 array
array2.shape

(3, 4)

In [10]:
array1.size

11

In [11]:
array2.size

12

# array 값을 균일한 값으로 생성 

**numpy** 모듈의 **full** 메소드를 사용하면, 모든 값이 같은 numpy array를 생성할 수 있다. 

In [12]:
array3 = np.full(5, 7)

print(array3)

[7 7 7 7 7]


# 모든 값이 0인 numpy array 생성  

모든 값이 0인 **numpy array** 를 생성하기 위해서는 **full** 메소드를 사용하면 된다. 

In [13]:
array4= np.full(6, 0)
array5 = np.zeros(6, dtype=int)

print(array4)
print()
print(array5)

[0 0 0 0 0 0]

[0 0 0 0 0 0]


# 모든 값이 0인 numpy array 생성
모든 값이 1인 **numpy array** 를 생성하는 것은 zeros 메소드 대신 **ones**를 사용하면 된다.

In [14]:
array6= np.full(6, 1)
array7 = np.ones(6, dtype=int)

print(array6)
print()
print(array7)

[1 1 1 1 1 1]

[1 1 1 1 1 1]


# 랜덤한 값들로 생성

어쩔 때는 임의의 값들로 배열을 생성시키고 싶습니다. 그럴 때는 **numpy의 random 모듈의 random 함수**를 사용하면 됩니다.

numpy 모듈 안에 **random**이라는 모듈이 있고, 그 안에 또 **random이라는 함수**가 있는 겁니다!

In [15]:
array8 = np.random.random(6)
array9 = np.random.random(6)
    
print(array8)
print()
print(array9)

[0.6097087  0.92266216 0.92891844 0.18070738 0.64162016 0.4475466 ]

[0.40719617 0.77426501 0.02882973 0.7394455  0.41061891 0.77890551]


# 연속된 값들이 담긴 numpy array 생성

numpy 모듈의 arange 함수를 사용하면 연속된 값들이 담겨 있는 numpy array를 생성할 수 있다.

arange 함수는 파이썬의 기본 함수인 range와 굉장히 비슷한 원리로 동작. 파라미터가 1개인 경우, 2개인 경우, 3개인 경우 모두 확인.

## 파라미터 1개

`arange(m)`을 하면 **0부터 m-1**까지 값들이 담긴 numpy array가 리턴된다.

In [16]:
array10 = np.arange(6)
print(array10)

[0 1 2 3 4 5]


## 파라미터 2개

`arange(n, m)`을 하면 **n부터 m-1**까지 값들이 담긴 numpy array가 리턴된다.

In [17]:
array11 = np.arange(2, 7)
print(array11)

[2 3 4 5 6]


## 파라미터 3개

`arange(n, m, s)`을 하면 **n부터 m-1**까지 값들 중 간격이 **s**인 값들이 담긴 numpy array가 리턴된다.

In [18]:
array12 = np.arange(3, 17, 3)
print(array12)

[ 3  6  9 12 15]


In [19]:
array12[0]

3

In [21]:
array12[-1]

15

In [25]:
array12[[1, 3, 4]]

array([ 6, 12, 15])

In [27]:
array12[0:4]

array([ 3,  6,  9, 12])

In [28]:
array12[:4]

array([ 3,  6,  9, 12])

In [29]:
array12[2:]

array([ 9, 12, 15])

In [31]:
array13 = np.arange(10)
array14 = np.arange(10, 20)
#numpy 문법을 사용하면 편하게 리스트의 덧셈 뺄셈 등의 사칙연산을 수행할 수 있다. 

In [32]:
array13 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [33]:
array13 / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [34]:
array13 + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [35]:
array13 ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [36]:
array13 + array14

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

# numpy 불린 연산



In [37]:
array15 = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

In [38]:
array15 > 4

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [39]:
array15 % 2 == 0

array([ True, False, False, False, False, False, False, False, False,
       False, False])

In [40]:
booleans = np.array([True, True, False, True, True, False, True, True, True, False, True])

In [41]:
# np.where: np array 에서 Ture인 Index(번호)만 불러옴 *주의: 값이 아님 
np.where(booleans)

(array([ 0,  1,  3,  4,  6,  7,  8, 10], dtype=int64),)

In [42]:
array15 > 4

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [43]:
# array15 중 4보다 큰 값을 가지는 인덱스 번호를 불러옴 
np.where(array15 > 4)

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64),)

In [44]:
filter = np.where(array15 > 4)
filter

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64),)

In [45]:
array15[filter]

array([ 5,  7, 11, 13, 17, 19, 23, 29, 31])